# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55fde129b5fd6282ec8289245261bd9638a5908a1e010b11908037780bd1e13df423c9148fa6eee60253a76cb7b5ca579d05cd0fa96a089f86fd1b556cbaaa8d

test:
  secret_key_base: b3752cd4bf753bb9356a73ee1a2cd479afb2e8bab7ea33382c1cfd76722708d7d74664f67fe22c8f3d9951eb88ec89da0728fb7c11c98ec353d85aca29cc5b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
